### ISSUE TITLE
more aggressive styles?

### ISSUE THREAD

**Issue by iambumblehead** [alphapapa/solarized-everything-css#45]
Hello and thank you for this project,

I found many pages resistant to the styles here, including common ones served from google and reddit. A few days ago I added more aggressive selectors to the darcula stylesheet and they vastly improved the effectiveness of the styles.

For example, these styles are at the top of the darcula css file I am using,
```css
html {
  background-color: #262626 !important;
}
html body,
html div,
html div * {
  background-color: #262626 !important;
  color: #909396 !important;
  text-shadow:none !important;
}
html body div * {
  border-color: #909396 !important;
  text-shadow:none !important;
}
html body div a {
  text-shadow:none !important;
  color: #ce4139 !important;
}
html body div a:visited {
  color: #b68800 !important;
}
html body input,
html body textarea {
  background-color: #2e2e2e !important;
  color: #909396 !important;
}
```

I recommend using 'stronger' names in the stylesheets here.
